#!/usr/bin/env python3
"""SensorForge firmware signing and key generation tool.

Creates cryptographically signed .sfw firmware packages for SD/WiFi updates.
The device verifies ECDSA P-256 / SHA-256 before an update can become bootable.
The private key stays on the release machine; only the public key is compiled
into SensorForge.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from pathlib import Path

try:
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec, utils
except ImportError as exc:
    raise SystemExit(
        "Missing dependency: cryptography\n"
        "Install it with:\n"
        "  python3 -m pip install cryptography"
    ) from exc

HEADER_SIZE = 128
MAGIC = b"SFWPKG1\0"
FORMAT_VERSION = 1
ALGORITHM_ECDSA_P256_SHA256 = 1
SIGNATURE_MAX = 72

DEFAULT_PRIVATE_KEY = "sensorforge_firmware_private.pem"
DEFAULT_PUBLIC_KEY = "sensorforge_firmware_public.pem"
DEFAULT_HEADER = "firmware_public_key.h"

BOARD_MARKERS = {
    "xiao": b"SENSORFORGE|ESP32S3|XIAO_SENSE|COMPAT=1",
    "freenove": b"SENSORFORGE|ESP32S3|FREENOVE_FNK0085|COMPAT=1",
}



def public_key_fingerprint(public_key) -> str:
    public_der = public_key.public_bytes(
        serialization.Encoding.DER,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return hashlib.sha256(public_der).hexdigest()


def resolve_header_path(explicit: str | None) -> Path:
    """Resolve the SensorForge public-key header deterministically.

    If --header is supplied, that exact path is used. Otherwise prefer an
    existing firmware_public_key.h next to the script, then in the current
    working directory. If neither exists, create it next to the script.
    """
    if explicit:
        return Path(explicit)

    script_dir = Path(__file__).resolve().parent
    candidates = [script_dir / DEFAULT_HEADER, Path.cwd() / DEFAULT_HEADER]
    seen = set()
    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        if candidate.exists():
            return candidate

    return script_dir / DEFAULT_HEADER


def write_public_key_header(public_key, header_path: Path) -> None:
    parent = header_path.parent
    if not parent.exists():
        raise ValueError(f"header directory does not exist: {parent}")

    public_pem = public_key.public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    fingerprint = public_key_fingerprint(public_key)
    pem_lines = public_pem.decode("ascii").splitlines()
    literals = "\n".join(f'    "{line}\\n"' for line in pem_lines)
    content = (
        "#pragma once\n\n"
        "// SensorForge firmware-update verification public key.\n"
        "// AUTO-GENERATED by sensorforge_firmware_sign.py - do not edit manually.\n"
        "// Algorithm: ECDSA P-256 / SHA-256\n"
        f"// Public-key SHA-256 fingerprint (DER): {fingerprint}\n"
        "// The matching private key must never be stored in firmware, on the SD\n"
        "// card, or in the source/release archive.\n"
        "static const char SENSORFORGE_FIRMWARE_PUBLIC_KEY_PEM[] =\n"
        f"{literals};\n"
    )

    tmp = header_path.with_name(header_path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(header_path)


def load_public_key(path: Path):
    if not path.exists():
        raise ValueError(f"public key not found: {path}")
    key = serialization.load_pem_public_key(path.read_bytes())
    if not isinstance(key, ec.EllipticCurvePublicKey) or not isinstance(
        key.curve, ec.SECP256R1
    ):
        raise ValueError("firmware public key must be ECDSA P-256 / secp256r1")
    return key

def detect_board(image: bytes) -> str:
    matches = [name for name, marker in BOARD_MARKERS.items() if marker in image]
    if len(matches) != 1:
        raise ValueError(
            "firmware must contain exactly one current SensorForge board compatibility marker"
        )
    return matches[0]


def load_private_key(path: Path):
    if not path.exists():
        raise ValueError(
            f"private key not found: {path}\n"
            f"Create the default key first with:\n"
            f"  python3 sensorforge_firmware_sign.py keygen"
        )

    key = serialization.load_pem_private_key(path.read_bytes(), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(
        key.curve, ec.SECP256R1
    ):
        raise ValueError("firmware signing key must be ECDSA P-256 / secp256r1")
    return key


def make_package(image: bytes, private_key) -> bytes:
    if not image or image[0] != 0xE9:
        raise ValueError("input is not an ESP32 application .bin (missing 0xE9 image magic)")
    if len(image) > 0xFFFFFFFF:
        raise ValueError("firmware image is too large for SFW package format v1")

    digest = hashlib.sha256(image).digest()
    signature = private_key.sign(
        digest,
        ec.ECDSA(utils.Prehashed(hashes.SHA256())),
    )
    if len(signature) > SIGNATURE_MAX:
        raise ValueError(f"unexpected ECDSA signature length: {len(signature)}")

    header = bytearray(HEADER_SIZE)
    header[0:8] = MAGIC
    header[8] = FORMAT_VERSION
    header[9] = ALGORITHM_ECDSA_P256_SHA256
    struct.pack_into("<H", header, 10, HEADER_SIZE)
    struct.pack_into("<I", header, 12, len(image))
    header[16:48] = digest
    struct.pack_into("<H", header, 48, len(signature))
    header[50 : 50 + len(signature)] = signature

    return bytes(header) + image


def verify_package(package: bytes, public_key) -> tuple[int, str]:
    if len(package) < HEADER_SIZE:
        raise ValueError("package is too short")
    header = package[:HEADER_SIZE]
    if header[:8] != MAGIC:
        raise ValueError("invalid package magic")
    if header[8] != FORMAT_VERSION or header[9] != ALGORITHM_ECDSA_P256_SHA256:
        raise ValueError("unsupported package format")
    if struct.unpack_from("<H", header, 10)[0] != HEADER_SIZE:
        raise ValueError("invalid package header size")

    image_size = struct.unpack_from("<I", header, 12)[0]
    if len(package) != HEADER_SIZE + image_size:
        raise ValueError("package size mismatch")
    digest = header[16:48]
    sig_len = struct.unpack_from("<H", header, 48)[0]
    if sig_len == 0 or sig_len > SIGNATURE_MAX:
        raise ValueError("invalid signature length")
    signature = header[50 : 50 + sig_len]
    image = package[HEADER_SIZE:]
    actual = hashlib.sha256(image).digest()
    if actual != digest:
        raise ValueError("SHA-256 mismatch")
    public_key.verify(signature, digest, ec.ECDSA(utils.Prehashed(hashes.SHA256())))
    return image_size, detect_board(image)


def command_sign(args: argparse.Namespace) -> int:
    image_path = Path(args.input)
    key_path = Path(args.key)
    output_path = Path(args.output) if args.output else image_path.with_suffix(".sfw")

    image = image_path.read_bytes()
    board = detect_board(image)
    if args.board and board != args.board:
        raise ValueError(f"firmware marker is for {board}, not requested board {args.board}")

    private_key = load_private_key(key_path)
    package = make_package(image, private_key)
    output_path.write_bytes(package)

    image_size, verified_board = verify_package(package, private_key.public_key())
    print(f"Created: {output_path}")
    print(f"Key:     {key_path}")
    print(f"Board:   {verified_board}")
    print(f"Image:   {image_size} bytes")
    print(f"SHA256:  {hashlib.sha256(image).hexdigest()}")
    return 0


def command_keygen(args: argparse.Namespace) -> int:
    private_path = Path(args.private)
    public_path = Path(args.public)

    existing = [path for path in (private_path, public_path) if path.exists()]
    if existing:
        names = ", ".join(str(path) for path in existing)
        raise ValueError(f"refusing to overwrite existing key file(s): {names}")

    header_path = None if args.no_header else resolve_header_path(args.header)

    key = ec.generate_private_key(ec.SECP256R1())
    private_pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.TraditionalOpenSSL,
        serialization.NoEncryption(),
    )
    public_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    private_path.write_bytes(private_pem)
    private_path.chmod(0o600)
    public_path.write_bytes(public_pem)

    if header_path:
        write_public_key_header(key.public_key(), header_path)

    print("New SensorForge firmware signing key pair created.")
    print(f"Private key: {private_path}")
    print(f"Public key:  {public_path}")
    if header_path:
        print(f"C++ header:  {header_path}  [updated automatically]")
        print(f"Fingerprint: {public_key_fingerprint(key.public_key())}")
        print("IMPORTANT: rebuild SensorForge after changing the header.")
    else:
        print("C++ header:  not changed (--no-header)")
    print("Keep the private key offline and never copy it to a device or source archive.")
    return 0


def command_update_header(args: argparse.Namespace) -> int:
    public_path = Path(args.public)
    header_path = resolve_header_path(args.header)
    public_key = load_public_key(public_path)
    write_public_key_header(public_key, header_path)

    print("SensorForge firmware public-key header updated.")
    print(f"Public key:  {public_path}")
    print(f"C++ header:  {header_path}")
    print(f"Fingerprint: {public_key_fingerprint(public_key)}")
    print("IMPORTANT: rebuild SensorForge after changing the header.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    description = f"""\
SensorForge firmware signing tool

Creates signed .sfw packages for SD/WiFi firmware updates and manages the
ECDSA P-256 signing key used by SensorForge.

Default files:
  private key: {DEFAULT_PRIVATE_KEY}
  public key:  {DEFAULT_PUBLIC_KEY}
  C++ header:  {DEFAULT_HEADER}

The 'keygen' command automatically updates firmware_public_key.h so the newly
generated public key is compiled into SensorForge on the next build.
"""

    epilog = f"""\
Typical workflow:

  1) Create a new signing key pair AND update firmware_public_key.h:
       python3 sensorforge_firmware_sign.py keygen

     Creates:
       {DEFAULT_PRIVATE_KEY}
       {DEFAULT_PUBLIC_KEY}

     And automatically updates/creates:
       {DEFAULT_HEADER}

  2) Rebuild SensorForge. The firmware now trusts that public key.

  3) Sign a compiled firmware image:
       python3 sensorforge_firmware_sign.py sign sensorforge.ino.bin

     Output:
       sensorforge.ino.sfw

  4) If a public PEM already exists and only the .h file must be synchronized:
       python3 sensorforge_firmware_sign.py update-header

Important:
  - Keep the PRIVATE key secret and outside source/release archives.
  - The PUBLIC key is not secret; firmware_public_key.h contains it.
  - Existing PEM key files are NEVER overwritten by keygen.
  - firmware_public_key.h IS intentionally replaced when keygen/update-header runs.
  - After changing firmware_public_key.h, rebuild SensorForge before using the new key.
  - Direct USB flashing of a normal .bin is not handled by this script.
"""

    parser = argparse.ArgumentParser(
        description=description,
        epilog=epilog,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    sign = sub.add_parser(
        "sign",
        help="sign an Arduino/ESP32 application .bin and create a .sfw package",
        description="Sign an ESP32 application image for SensorForge SD/WiFi update.",
        epilog=f"""\
Examples:
  python3 sensorforge_firmware_sign.py sign sensorforge.ino.bin
  python3 sensorforge_firmware_sign.py sign sensorforge.ino.bin --board xiao
  python3 sensorforge_firmware_sign.py sign sensorforge.ino.bin --key other_private.pem
  python3 sensorforge_firmware_sign.py sign sensorforge.ino.bin --output release.sfw

If --key is omitted, '{DEFAULT_PRIVATE_KEY}' is used.
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sign.add_argument("input", help="compiled ESP32 application .bin")
    sign.add_argument(
        "--key",
        default=DEFAULT_PRIVATE_KEY,
        help=f"ECDSA P-256 private PEM key (default: {DEFAULT_PRIVATE_KEY})",
    )
    sign.add_argument("--output", help="output .sfw path (default: input name with .sfw)")
    sign.add_argument("--board", choices=sorted(BOARD_MARKERS), help="optional board assertion")
    sign.set_defaults(func=command_sign)

    keygen = sub.add_parser(
        "keygen",
        help="generate keys and automatically update firmware_public_key.h",
        description=(
            "Generate a new SensorForge ECDSA P-256 key pair and, by default, "
            "automatically update firmware_public_key.h."
        ),
        epilog=f"""\
Examples:
  python3 sensorforge_firmware_sign.py keygen
  python3 sensorforge_firmware_sign.py keygen --private production_private.pem --public production_public.pem
  python3 sensorforge_firmware_sign.py keygen --header path/to/firmware_public_key.h
  python3 sensorforge_firmware_sign.py keygen --no-header

Default behavior:
  - creates {DEFAULT_PRIVATE_KEY}
  - creates {DEFAULT_PUBLIC_KEY}
  - finds and replaces {DEFAULT_HEADER} next to this script
  - if the header does not yet exist, creates it next to this script
  - refuses to overwrite existing PEM key files

After keygen, REBUILD SensorForge before signing/installing firmware with the
new key.
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    keygen.add_argument(
        "--private",
        default=DEFAULT_PRIVATE_KEY,
        help=f"new private PEM path (default: {DEFAULT_PRIVATE_KEY})",
    )
    keygen.add_argument(
        "--public",
        default=DEFAULT_PUBLIC_KEY,
        help=f"new public PEM path (default: {DEFAULT_PUBLIC_KEY})",
    )
    header_group = keygen.add_mutually_exclusive_group()
    header_group.add_argument(
        "--header",
        help=f"C++ header to update (default: auto-detect {DEFAULT_HEADER})",
    )
    header_group.add_argument(
        "--no-header",
        action="store_true",
        help="generate PEM keys only; do not change firmware_public_key.h",
    )
    keygen.set_defaults(func=command_keygen)

    update_header = sub.add_parser(
        "update-header",
        help="update firmware_public_key.h from an existing public PEM key",
        description=(
            "Synchronize firmware_public_key.h with an existing ECDSA P-256 public PEM key."
        ),
        epilog=f"""\
Examples:
  python3 sensorforge_firmware_sign.py update-header
  python3 sensorforge_firmware_sign.py update-header --public production_public.pem
  python3 sensorforge_firmware_sign.py update-header --header path/to/firmware_public_key.h

Defaults:
  public key: {DEFAULT_PUBLIC_KEY}
  header:     auto-detected {DEFAULT_HEADER} next to this script
""",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    update_header.add_argument(
        "--public",
        default=DEFAULT_PUBLIC_KEY,
        help=f"public PEM path (default: {DEFAULT_PUBLIC_KEY})",
    )
    update_header.add_argument(
        "--header",
        help=f"C++ header to update (default: auto-detect {DEFAULT_HEADER})",
    )
    update_header.set_defaults(func=command_update_header)

    return parser


def main() -> int:
    parser = build_parser()

    if len(sys.argv) == 1:
        parser.print_help()
        return 0

    args = parser.parse_args()
    if not hasattr(args, "func"):
        parser.print_help()
        return 0

    try:
        return args.func(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
